### ISSUE TITLE
schemaRegistry.url cache

### ISSUE THREAD

**Issue by 9yx** [ImFlog/schema-registry-plugin#23] opened 2019-04-25 10:06 UTC
I use gradle 5.3.1, schema-registry-plugin 0.5.0, if I change the schemaRegistry.url, then the url address does not change until I turn off the cache in gradle
./gradlew registerSchemaTask --no-build-cache

**Comment by ImFlog** [comment] 2019-04-26 10:07
Hello, thank you for your interest in this plugin.
It indeed looks like a bug, I recently made a lot of change around the way we handle the client wrapper and looking at the code the url is marked as `@Input` so it should not be cached.

I am planning a release next week (probably around wednesday) after a bit more refactoring, I will ping you afterward and see if it still fails on your side. :)

**Comment by ImFlog** [comment] 2019-05-01 19:11
I successfully reproduced the bug locally with the old version. With the new version the problem doesn't appear. The version 0.6.0 is now awaiting approval.
Please test it when available and tell me if I can close this issue ;)

**Closed** 2019-05-05 09:50 UTC
