### ISSUE TITLE
Registry task fails after updating to 1.9.0 from 1.8.0

### ISSUE THREAD

**Issue by martinformi** [ImFlog/schema-registry-plugin#131] opened 2023-04-26 12:17 UTC
This was working with 1.8.0:
**gradle**
```
schemaRegistry {
    url = 'https://zzz'

    register {

        subject('ccc.SomeItem', 'src/main/avro/SomeItem.avsc', 'AVRO').addLocalReference('SomeItem', 'src/main/avro/SomeItem.avsc')
```

**SomeItem.avsc**
```
{
  "type": "record",
  "namespace": "xxx",
  "name": "SomeItem",
  "version": "1",
  "fields": [
    {
      "name": "timestamp",
      "type": "long"
    },
    {
      "name": "value",
      "type": "double"
    }
  ]
}
```
With 1.9.0 we are getting:
```
* What went wrong:
Execution failed for task ':commons::registerSchemasTask'.
> 'java.util.Set org.json.JSONObject.keySet()'
```
We downgraded back to 1.8.0.

**Comment by ImFlog** [comment] 2023-04-26 13:21
Hello,
Thank you for using the plugin.

Can you elaborate on what's in the original subject and what's in the local subject (redacted) ? In the example it is referenced twice (as output and as reference) :
`subject('ccc.SomeItem', 'src/main/avro/SomeItem.avsc', 'AVRO').addLocalReference('SomeItem', 'src/main/avro/SomeItem.avsc')`
It would help me reproduce and then fix.
Thank you.

**Comment by emmeblm** [comment] 2023-05-06 09:56
Hi,

I am getting the exact same error on version 1.9.0.

Here's an example of my setup:

```groovy
subject("com.example.some.task.tasks-value",
        "src/main/avro/task.avsc",
        "AVRO")
.addLocalReference("Recurrence", 
                   "src/main/avro/recurrence.avsc")
```

**Comment by ImFlog** [comment] 2023-07-12 22:58
Hello @martinformi and @emmeblm. I've just released the version 1.11.1. Can you try with this version to see if the issue was related ?
NB: It requires to add Jitpack in the build repository because we are now using a custom Avro version to allow us to handle correctly local + remote dependency mixing in Avro.
Thanks

**Comment by emmeblm** [comment] 2023-07-13 08:07
Hi @ImFlog 

Version 1.11.1 seems to have solved the issue for me. Thanks!

**Comment by ImFlog** [comment] 2023-07-21 06:01
I'm closing this then, if anything still fail for you @martinformi do not hesitate to reopen an issue.

**Closed by ImFlog** 2023-07-21 06:01 UTC
